### ISSUE TITLE
如何快速移植

### ISSUE THREAD

**Issue by sdreamforchen** [Chasel-Tsui/mmdet-rfla#1]
校友，您好。想请问下，我想移植label assign部分到我的pytorch代码里面。想请问下，我应该关注哪些代码或者python文件？
Thanks！

**Comment by Chasel-Tsui** [comment]
> 校友，您好。想请问下，我想移植label assign部分到我的pytorch代码里面。想请问下，我应该关注哪些代码或者python文件？ Thanks！

双阶段算法主要关注mmdet/core/bbox/assigner下的assigner文件，mmdet/core/bbox/iou_calculators下的距离计算文件，以及mmdet/core/anchor下的rf生成文件；单阶段除这些外还有mmdet/models/dense_heads下相应的detection head

**Comment by MacchiatoTea** [comment]
校友您好！我也想将部分代码移植到yolo系列当中，方便加联系方式一起讨论交流吗？谢谢！

**Comment by Chasel-Tsui** [comment]
> 校友您好！我也想将部分代码移植到yolo系列当中，方便加联系方式一起讨论交流吗？谢谢！

您好，方便的话可以加QQ1363060527

**Comment by davidsvy** [comment]
Hello @sdreamforchen. Have you succeeded adding RFLA to your codebase? If so, can you please tell me how you estimated the receptive field (either theoretical or effective) for intermediate layers of different architectures?
