### ISSUE TITLE
Will the RFLA increase the False Negative?

### ISSUE THREAD

**Issue by freshn** [Chasel-Tsui/mmdet-rfla#12]
Hi. I am wondering if the RFLA increases the number of false negatives. From Fig 1 it seems RFLA will have more blue bounding boxes than its counterparts. Is that a coincidence or not?

**Comment by Chasel-Tsui** [comment]
The blue boxes denote false positive (FP) predictions, rfla may lead to more  FP for densely arranged objects/objects missed to be annotated.

**Comment by freshn** [comment]
Thank you for your reply. Yes I mean Flase Positive.
