### ISSUE TITLE
在其他模型中加入rfla

### ISSUE THREAD

**Issue by little-spoon** [Chasel-Tsui/mmdet-rfla#13]
您好，如果我想在其他模型（例如vfnet,tood,gfl等）中加入rfla，我应该重点关注哪些文件的修改呢？谢谢！

**Comment by Chasel-Tsui** [comment]
主要包括mmdet/core/bbox/iou_calculators下的距离计算文件，以及mmdet/core/anchor下的rf生成文件，对于这些单阶段算法，除这些外还要适配mmdet/models/dense_heads下相应的detection head，特别是里面的get_targets函数

**Comment by little-spoon** [comment]
好的谢谢

**Comment by yuhua666** [comment]
请问您成功了吗
