### ISSUE TITLE
請問是否有模型預訓練權重可以提供引用? 謝謝您!

### ISSUE THREAD

**Issue by CCChiu0419** [Chasel-Tsui/mmdet-rfla#15]

**Comment by Chasel-Tsui** [comment]
Yes, of course. I will organize the pre-trained models these days and release them in a few days.

**Comment by CCChiu0419** [comment]
Thanks a lot.

**Comment by Chasel-Tsui** [comment]
Hi, we have released the pre-trained models, see [onedrive](https://1drv.ms/u/s!Ao5UiAkIbGJ7xRGZ3AYB7IW8zas2?e=opfU3x)
