### ISSUE TITLE
 请问有COCO数据集的实验结果吗

### ISSUE THREAD

**Issue by Watebear** [Chasel-Tsui/mmdet-rfla#2]
请问作者，在coco上跟 atss，ota等匹配方法做过对比吗？效果如何？

**Comment by Chasel-Tsui** [comment]
> 请问作者，在coco上跟 atss，ota等匹配方法做过对比吗？效果如何？

没有在coco上跑过，coco里面的极小目标数量很少（<16*16）,coco里的目标大多集中在32*32左右，基本都能分到数量可观的正样本，这个方法可能并不适合coco。
