### ISSUE TITLE
关于aitodv2

### ISSUE THREAD

**Issue by Mr-Bigworth** [Chasel-Tsui/mmdet-rfla#21]
请问aitodv2数据和aitodv1的数据只是标注存在差异对不

**Comment by Chasel-Tsui** [comment]
是的

**Comment by Mr-Bigworth** [comment]
> 是的

嗯嗯，那请问config中的small_trainval_v2_2.0.json和small_test_v2_2.0.json是怎样得到的呢，我看aitodv2的链接只提供了aitodv2_train.json和aitodv2_val.json
https://drive.google.com/drive/folders/1Er14atDO1cBraBD4DSFODZV1x7NHO_PY

**Comment by Mr-Bigworth** [comment]
已解决
