### ISSUE TITLE
RFGenerator

### ISSUE THREAD

**Issue by yuhua666** [Chasel-Tsui/mmdet-rfla#27]
博士您好，感谢你们出色的工作！
我注意到您的代码中有一段计算Resnet-50-FPN的感受野的过程，即RFGenerator class下的def gen_trf(self):函数，这看上去是只适用于Resnet-50-FPN的，我应该如何修改代码使之适应其他backbone呢？例如Resnet-18，希望可以得到您的指导，感谢。

**Comment by Chasel-Tsui** [comment]
可以根据[ResNet网络结构](https://blog.csdn.net/weixin_41560402/article/details/108996514)计算，或直接使用[别人公开的数据](https://gist.github.com/samson-wang/a6073c18f2adf16e0ab5fb95b53db3e6)

**Comment by yuhua666** [comment]
感谢您的指导，我还有一个问题，论文中图1的结果是怎么生成的呢，就是用绿框、蓝框、红框分别代码检测正确、误检、漏检。
这个问题是源于我注意到rfla给faster rcnn+resnet50带来了更多的误检，我想检查一下当rfla用于我的网络中时(已成功应用)，是否也会这样。
希望能够得到您的再次指导，十分感谢。

**Comment by Chasel-Tsui** [comment]
图一的结果需要将生成的prediction和gt进行匹配，进而划分检测正确、误检、漏检，然后进行可视化。rfla确实有可能带来更多的误检。

**Comment by yuhua666** [comment]
感谢，请问您是通过什么软件或代码生成的呢？我想自己去尝试生成一下。
