### ISSUE TITLE
About eq6(关于公式6)

### ISSUE THREAD

**Issue by little-spoon** [Chasel-Tsui/mmdet-rfla#28]
请问公式6中tr是没有下标吗，那么它与后面的部分是做的什么运算？
还有就是为什么∑符号后面没有内容呢，它在对什么求和？
以及为什么∑g的上界是-1呢？这代表了什么意思？
感谢回答

**Comment by Chasel-Tsui** [comment]
你好，tr的全称是trace，指的是矩阵的迹。这里的\Sigma是高斯分布的协方差矩阵，而不是求和符号，\Sigma_{g}^{-1}的-1指的是-1次方~

**Comment by little-spoon** [comment]
谢谢！是我线性代数没学好。。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chasel-Tsui/mmdet-rfla"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月19日(星期四) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chasel-Tsui/mmdet-rfla] About eq6(关于公式6) (Issue #28)





 
你好，tr的全称是trace，指的是矩阵的迹。这里的\Sigma是高斯分布的协方差矩阵，而不是求和符号，\Sigma_{g}^{-1}的-1指的是-1次方~
