### ISSUE TITLE
旋转框检测引入rfla

### ISSUE THREAD

**Issue by CrazyTanFB** [Chasel-Tsui/mmdet-rfla#29]
请教下，旋转框检测引入rfla，旋转gt框和感受野bbox怎么算wd和kld呢？

**Comment by Chasel-Tsui** [comment]
你好，主要应该关注[metric_calculator](https://github.com/Chasel-Tsui/mmdet-rfla/blob/main/mmdet/core/bbox/iou_calculators/metric_calculator.py)文件，并在高斯建模时添加角度参数，对旋转框进行适配。另外，DOTA-OBB这样的多尺度旋转目标检测数据集和AI-TOD不太一样，建议1.将k增大到6以上 2.添加约束滤除远离gt的低质量样本。

**Comment by CrazyTanFB** [comment]
> 你好，主要应该关注[metric_calculator](https://github.com/Chasel-Tsui/mmdet-rfla/blob/main/mmdet/core/bbox/iou_calculators/metric_calculator.py)文件，并在高斯建模时添加角度参数，对旋转框进行适配。另外，DOTA-OBB这样的多尺度旋转目标检测数据集和AI-TOD不太一样，建议1.将k增大到6以上 2.添加约束滤除远离gt的低质量样本。

好的，多谢多谢
