### ISSUE TITLE
关于RFD和阶段因子的理解

### ISSUE THREAD

**Issue by little-spoon** [Chasel-Tsui/mmdet-rfla#30]
您好，在阅读论文是我对RFD的含义有一些不理解的地方，希望能得到您的回答：

（1）在论文中提到用感受野距离(RFD)来直接测量高斯感受野与GT之间的相似度，后文提到用KL散度来作为感受野距离候选，请问公示6计算出来的值与RFD之间是什么关系呢？这个“距离”到底是指的什么距离呢？
（2）如果不使用Wasserstein距离作为感受野距离候选（即不存在候选的概念），公示8是否能直接写作RFD=1/(1+RFD)?
（3）3.3 节中提到的特征点与gt直接RFD评分矩阵，这个“分数”是值公式6计算的结果吗？如果不是，那是指什么呢？
（4）关于掩码m，是否表示当这个特征点被赋值正标签后，对应的m的值为1，否则为0？
（5）在图1中的画出的RFD，是一个具象的表示特征点与gt之间距离的值吗？还是一个抽象的衡量正态分布感受野与gt直接相似度的值？图中所表现出的“高度”，是否是指“该处对检测的贡献大小（即权重）”？

（6）关于阶段因子β，为什么乘以β以后就可以提高召回率减少异常值呢？

非常感谢您能回答我的问题，祝您生活愉快！

**Comment by Chasel-Tsui** [comment]
您好，感谢关注
(1)对公式6进行归一化后是可以选择的RFD之一，RFD越大则越相似
(2)可以，这里的RFDC是为了区分归一化前的值和归一化后的
(3)是的，计算gt和特征点的相似度的时候可以得到一个矩阵，这里的矩阵的每一行表示一个gt，每一列表示一个特征点，矩阵里的每一个元素都是RFD，即分数
(4)是的
(5)图1中的RFD即公式8计算出来的值，可以理解为该处的特征点对检测的贡献大小
(6)这里是一个启发式操作，特别是在AI-TODv2上，可能有部分gt和其他gt共享特征点，一次匹配无法获得足够的特征点。乘以beta后再匹配一次能补足一些样本。个人觉得这个地方有一些改进空间，比如在训练过程中动态计算感受野，然后再计算距离，可能会准确一些，不过会带来一些额外计算开销。

**Comment by little-spoon** [comment]
感谢您的回答！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Chasel-Tsui/mmdet-rfla"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月8日(星期三) 中午1:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Chasel-Tsui/mmdet-rfla] 关于RFD和阶段因子的理解 (Issue #30)





 
您好，感谢关注
 (1)对公式6进行归一化后是可以选择的RFD之一，RFD越大则越相似
 (2)可以，这里的RFDC是为了区分归一化前的值和归一化后的
 (3)是的，计算gt和特征点的相似度的时候可以得到一个矩阵，这里的矩阵的每一行表示一个gt，每一列表示一个特征点，矩阵里的每一个元素都是RFD，即分数
 (4)是的
 (5)图1中的RFD即公式8计算出来的值，可以理解为该处的特征点对检测的贡献大小
 (6)这里是一个启发式操作，特别是在AI-TODv2上，可能有部分gt和其他gt共享特征点，一次匹配无法获得足够的特征点。乘以beta后再匹配一次能补足一些样本。个人觉得这个地方有一些改进空间，比如在训练过程中动态计算感受野，然后再计算距离，可能会准确一些，不过会带来一些额外计算开销。
