### ISSUE TITLE
关于aitodpycocotools速度问题

### ISSUE THREAD

**Issue by Meize0729** [Chasel-Tsui/mmdet-rfla#31]
您好，请问为什么train之后的使用aitodpycocotools的evaluation耗时很久呢？是我的程序出现问题了吗

**Comment by Chasel-Tsui** [comment]
确实耗时挺久，我用Faster R-CNN在test set上验证一下要接近1小时(3090)，单阶段模型更久。aitodpycocotools算的指标多，并且增大了maxdet以及max_per_img，如果想要减少测试时间可以调小max_per_img，不过性能会掉1~2个点。

**Comment by Meize0729** [comment]
感谢您的回答，感谢您的工作
