### ISSUE TITLE
RFGenerator计算感受野

### ISSUE THREAD

**Issue by yuhua666** [Chasel-Tsui/mmdet-rfla#32]
博士您好，我根据您上次提供给我的不同型号resnet的计算方式修改了感受野的计算(我使用的网络是resnet18)，然而修改后相比原先(resnet50版本的感受野计算方式)下降了一点性能，您知道大致原因吗？我修改的代码如下：
`
def gen_trf(self):
        j_i = [1]
        for i in range(7):
            j = j_i[i]*2
            j_i.append(j)

        trf_p2 = 43

        trf_p3 = 99

        trf_p4 = 211

        trf_p5 = 435
 
        trf_p6 = trf_p5 + (3-1)*j_i[6]

        trf_p7 = trf_p6 + (3-1)*j_i[7]

        trfs = [trf_p2, trf_p3, trf_p4, trf_p5, trf_p6, trf_p7]

        return trfs`

**Comment by Chasel-Tsui** [comment]
这里的下降，指的是在res18上训练的时候，用res18的计算方式，相比于res50的计算方式性能下降吗

**Comment by yuhua666** [comment]
是的，这可能是有效感受野与实际感受野不同造成的吗？

**Comment by Chasel-Tsui** [comment]
有可能的，你可以试一下调节fraction为1/3试一下。另外，如果有办法能够在训练过程中动态估计感受野，会是一个很好的工作。

**Comment by yuhua666** [comment]
感谢，我将根据您的建议进一步尝试。

**Comment by yuhua666** [comment]
> 有可能的，你可以试一下调节fraction为1/3试一下。另外，如果有办法能够在训练过程中动态估计感受野，会是一个很好的工作。

似乎有效，但只相比用res50的计算方式提升了0.1%，还有其他的参数可以调节吗？

**Comment by Chasel-Tsui** [comment]
fraction以及assigner中topk的第一个参数都可以调节试一下
