### ISSUE TITLE
关于baseline是否收敛的问题

### ISSUE THREAD

**Issue by Meize0729** [Chasel-Tsui/mmdet-rfla#33]
您好，使用focs作为检测器epoch=12时，我关注到baseline并未收敛，repeatdataset=2，即训练24回合，得到的baseline是提高的，且提高百分比在50%！证明12回合并未完全收敛。在这种未收敛的epoch下使用rfla做对比是否显的不公平呢。是否应该在完全收敛或接近完全收敛的epoch下做对比呢。
希望得到您的回复，感谢

**Comment by Chasel-Tsui** [comment]
fcos和rfla使用的是同样的1x training setting (12 epochs)，这样的比较是公平的。在检测领域大部分数据集上，例如COCO, DOTA, VOC，2x training也能带来明显的增益，但是大部分基于CNN的paper都是固定训练epoch为1x，然后比较性能。一般来说，只要能在同样的epoch(一般为1x)下有提升，即可说明方法的有效性。

**Comment by Chasel-Tsui** [comment]
关于收敛性，我重新测试了一下2x setting下的性能，RFLA+FCOS也是要比FCOS好很多的
