### ISSUE TITLE
关于Faster-RCNN在visdrone数据集的相关疑问

### ISSUE THREAD

**Issue by Meize0729** [Chasel-Tsui/mmdet-rfla#34]
您看您方便提供您的在visdrone数据集上使用Faster-RCNN的baseline的config吗，我想了解您的baseline的相关train set，您看是否方便呢，只需baseline即可

**Comment by Chasel-Tsui** [comment]
可以参考一下这个[issue](https://github.com/Chasel-Tsui/mmdet-rfla/issues/19), 需要自己将标注转换成json格式哈
