### ISSUE TITLE
关于aitod-v2

### ISSUE THREAD

**Issue by Meize0729** [Chasel-Tsui/mmdet-rfla#36]
抱歉反复打扰您，关注到您是也是aitod数据集的制作者，想了解一下aitodv2是不再提供test数据集了吗，test数据集使用和aitodv1一样的吗
希望得到您的回复
祝好

**Comment by Chasel-Tsui** [comment]
test set和aitod1不一样，目前还没发布，之前打算用它来举办比赛，但因为资源有限一直没能组织起来。。。所以可以直接在aitodv2 train set上训练，报告val set上的测试性能

**Comment by Meize0729** [comment]
很感激您的回复，武汉大学在遥感数据集上的工作很棒，包括aitod和dota，您的工作在two-stage的效果也很显著，我也在上述的TOD数据集上不断完善我的工作，不知是否方便添加您的私人联系方式仅用于学术交流，如若方便还烦请您联系wmz20000729@buaa.edu.cn这个邮箱账号。
感激您的回复与帮助，谢谢！
祝好！

**Comment by Chasel-Tsui** [comment]
您好，感谢关注和对本工作的认可，已联系以上邮箱~
