### ISSUE TITLE
Pretrained Models的链接打不开

### ISSUE THREAD

**Issue by realfzyyyyy** [Chasel-Tsui/mmdet-rfla#37]
作者您好！Pretrained Models的链接打不开啦，可以麻烦更新一下吗？

**Comment by Chasel-Tsui** [comment]
您好，我刚刚确认了一下还是有效的，需要连接VPN才能打开

**Comment by Smellly** [comment]
![image](https://github.com/user-attachments/assets/55cc805e-9462-44dc-9764-79f6041b4d41)
打不开了
