### ISSUE TITLE
小目标检测bbox与GT的iou过小导致最终mAP为0

### ISSUE THREAD

**Issue by WooXinyi** [Chasel-Tsui/mmdet-rfla#43]
按照初始配置在自定义数据训练完模型后，跑一批图片发现bbox与GT的iou过小，最终mAP为0，初步判断是anchor设置不对导致。请问作者在训练时anchor做过调整吗？
例如：

![09750](https://user-images.githubusercontent.com/31875617/226822424-38405a2f-5c9f-4eba-8635-8ff5512e11be.jpg)

**Comment by Chasel-Tsui** [comment]
我感觉可能不是anchor的问题，因为在RFLA策略下，不管先验点或者anchor设置的怎么样，总能匹配到一些正样本进行训练。产生这样的预测结果有可能有以下原因供参考:
（1）训练集中的标签是怎么样的，有没有可能训练集中存在大量的标签包含了背景区域，使得网络拟合的实际上是如图所示的包含背景区域的目标。
（2）网络是否存在欠拟合问题。回归loss是否明显下降，如果数据量比较小的话可以延长训练时间，如果前几个epoch回归loss没有明显下降建议重新训练，另外可以用DIoU Loss加速收敛。
（3）mAP为0是指整个检测结果的mAP都是0吗，如果是这样的话可能是训练的网络没收敛。

**Comment by WooXinyi** [comment]
找到原因了，是因为数据增强用了Distortion，去掉后就正常了
