### ISSUE TITLE
RFLA用于retinanet的配置文件

### ISSUE THREAD

**Issue by yuhua666** [Chasel-Tsui/mmdet-rfla#46]
你好，请问有retinanet的rfla配置文件吗，我自己写的跑出来loss为nan。。。

**Comment by yuhua666** [comment]
您好，可以在开源代码中补充retinanet关于rfla检测头的代码吗？

**Comment by Chasel-Tsui** [comment]
您好，已更新，见[retinanet_rfla](https://github.com/Chasel-Tsui/mmdet-rfla/blob/main/configs/rfla/aitod_retinanet_r50_rfla_kld_1x.py)

**Comment by yuhua666** [comment]
非常感谢！
