### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by austin1900** [Chasel-Tsui/mmdet-rfla#48]
作者您好，请问您方便共享下表5里配置了RFLA方法的检测器每个类的性能指标吗。

**Comment by Chasel-Tsui** [comment]
您好，已更新，见[classwise_AP](https://github.com/Chasel-Tsui/mmdet-rfla/blob/main/output/classwise.txt)

**Comment by TinyOD** [comment]
谢谢
