### ISSUE TITLE
运行autoassign时报错

### ISSUE THREAD

**Issue by austin1900** [Chasel-Tsui/mmdet-rfla#49]
您好，当我运行aitod_autoassign_r50_rfla_kld_1x.py时报错：
  File "/data/mmdet-rfla-main/mmdet/models/dense_heads/rfla_autoassign_head.py", line 429, in loss
    if inside_gt_bbox_mask_list[i].any():
RuntimeError: all only supports torch.uint8 and torch.bool dtypes
而运行aitod_autoassign_r50_1x.py时不会报错，请问要如何解决呢，谢谢。

**Comment by Chasel-Tsui** [comment]
这个问题我也不太清楚，我跑的时候没碰到过

**Comment by TinyOD** [comment]
谢谢
