### ISSUE TITLE
运行python tools/train.py configs/rfla/aitod_faster_r50_rfla_wd_1x.py会报错

### ISSUE THREAD

**Issue by fppccc** [Chasel-Tsui/mmdet-rfla#5]
作者，您好！我想试着运行您的代码，在配置好环境后（所有requirements均已满足），我在终端输入python tools/train.py configs/rfla/aitod_faster_r50_rfla_wd_1x.py的指令，报错为“KeyError: "RPNHead: ' HieAssigner is not in the bbox_ assigner registry
”，请问是否是我的步骤有错误？感谢！

**Comment by XiaoyuWant** [comment]
我也有这个问题，没有用过mmdetection，不知道怎么解决。安装的是mvccfull & pytorch 1.10.2

**Comment by hezheyuan** [comment]
我以为是这个问题

**Comment by Chasel-Tsui** [comment]
有可能是因为在该环境下同时安装了mmdet和mmdet-rfla，这样会导致环境检索到原来的mmdet，建议卸载重复的mmdet试一下

**Comment by XiaoyuWant** [comment]
是这个原因，重装了一下问题解决了 ：）
