### ISSUE TITLE
请教一下mmdet和mmcv-full的具体版本。

### ISSUE THREAD

**Issue by FiresWorker** [Chasel-Tsui/mmdet-rfla#62]
请教一下mmdet和mmcv-full的具体版本，现在最新的mmdet3.0和mmcv-full2.0会有模块无法导入，例如mmcv.runner

**Comment by MissMIA0** [comment]
mmdet下面version.py里有 __version__ = '2.13.0'

**Comment by FiresWorker** [comment]
mmdet 2.13.0
mmcv-full 1.4.0
