### ISSUE TITLE
Rotated bounding box.

### ISSUE THREAD

**Issue by ZhenboZhao77** [Chasel-Tsui/mmdet-rfla#70]
What I want to do is to detect small targets with rotated bounding boxes on the DOTA and Data1.5 datasets. Can this method be applied? Are there any suggestions or advice?

**Comment by Chasel-Tsui** [comment]
Hi, thanks for your question. I found a paper called "Orientation Detector for Ship Targets in SAR Images Based on Semantic Flow Feature Alignment and Gaussian Label Matching" that applies the RFLA's core idea to rotated bounding boxes in SAR images, maybe you can check it for details
